#   A
#  / \
# B   C
#  \ /
#   D
name: Diamond
inputs:
  - name: input
    size: 100MB
outputs:
  - name: result
    source: D.result
tasks:
  - name: A
    inputs:
      - name: input
        source: data1
    outputs:
      - name: result1
        size: 1000MB
    requirements:
      cpu: 1
      memory: 1GB
    size: 500GF
  - name: B
    inputs:
      - name: result1
        source: data2
    outputs:
      - name: result2
        size: 5MB
    requirements:
      cpu: 1
      memory: 2GB
    size: 200GF
  - name: C
    inputs:
      - name: result1
        source: data3
    outputs:
      - name: result3
        size: 1MB
    requirements:
      cpu: 2
      memory: 2GB
    size: 300GF
  - name: D
    inputs:
      - name: result3
        source: B.result
      - name: result2
        source: C.result
    outputs:
      - name: result
        size: 1MB
    requirements:
      cpu: 1
      memory: 1GB
    size: 100GF
